apiVersion: v1
kind: Service
metadata: 
  name: {{ include "enterprise-platform-chart.fullname" . }} 
  labels:
   {{- include "enterprise-platform-chart.labels" . | nindent 4 }} 
spec:
     type: {{ .Values.service.type }}
     selector:
        app.kubernetes.io/name: {{ include "enterprise-platform-chart.name" . }} 
        app.kubernetes.io/instance: {{ .Release.Name }}
     ports: 
        - port: {{ .Values.service.port}}
          targetPort: {{ .Values.containerPort }}
          protocol: TCP
          name: http
